// <auto-generated />
using System;
using MVCBudget.Forser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBudget.Forser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231021075323_InitialFreshCreateWithData")]
    partial class InitialFreshCreateWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCBudget.Forser.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gasoline"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rent/Mortgage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Home Improvement"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Savings"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Investments"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Charity"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("MVCBudget.Forser.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TransferredAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserWalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserWalletId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Weekly grocery expenses",
                            Name = "Grocery Shopping",
                            TransactionDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -50.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Dining out with friends",
                            Name = "Dinner at Pizzeria",
                            TransactionDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -30.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Car fuel refill",
                            Name = "Gas Refill",
                            TransactionDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -40.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Monthly electricity bill",
                            Name = "Electric Bill",
                            TransactionDate = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -70.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Monthly rent for apartment",
                            Name = "Rent Payment",
                            TransactionDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -1200.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Entertainment expenses",
                            Name = "Movie Tickets",
                            TransactionDate = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -25.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Medical check-up copay",
                            Name = "Doctor's Visit",
                            TransactionDate = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -40.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Public transportation cost",
                            Name = "Bus Fare",
                            TransactionDate = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -10.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "Footwear purchase",
                            Name = "New Shoes",
                            TransactionDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -60.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "New laptop for work",
                            Name = "Laptop Purchase",
                            TransactionDate = new DateTime(2021, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -800.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 11,
                            Description = "Fixing plumbing issues",
                            Name = "Home Repairs",
                            TransactionDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -150.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 12,
                            Description = "Gift for a friend's birthday",
                            Name = "Birthday Gift",
                            TransactionDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -20.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 13,
                            Description = "Short trip with family",
                            Name = "Weekend Getaway",
                            TransactionDate = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -300.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 14,
                            Description = "Monthly insurance premium",
                            Name = "Health Insurance",
                            TransactionDate = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -80.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 15,
                            Description = "Purchase of college textbooks",
                            Name = "Textbooks",
                            TransactionDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -150.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 16,
                            Description = "Adding to savings account",
                            Name = "Savings Deposit",
                            TransactionDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = 200.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 17,
                            Description = "Investing in mutual funds",
                            Name = "Investment Fund",
                            TransactionDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = 500.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 18,
                            Description = "Contribution to a local charity",
                            Name = "Charity Donation",
                            TransactionDate = new DateTime(2021, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -30.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 19,
                            Description = "Buying food and toys for pets",
                            Name = "Pet Supplies",
                            TransactionDate = new DateTime(2022, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -45.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 20,
                            Description = "Random miscellaneous expense",
                            Name = "Miscellaneous",
                            TransactionDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -15.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Morning coffee and pastries",
                            Name = "Coffee Shop",
                            TransactionDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -8.50m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Weekly grocery expenses",
                            Name = "Grocery Shopping",
                            TransactionDate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -60.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Monthly internet subscription",
                            Name = "Internet Bill",
                            TransactionDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -55.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Entertainment expenses",
                            Name = "Movie Tickets",
                            TransactionDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -20.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "Dental check-up copay",
                            Name = "Dentist Appointment",
                            TransactionDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -60.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Description = "Public transportation cost",
                            Name = "Subway Fare",
                            TransactionDate = new DateTime(2022, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -5.50m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            Description = "Purchase of winter jacket",
                            Name = "New Jacket",
                            TransactionDate = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -70.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            Description = "Upgrading to the latest model",
                            Name = "Smartphone Upgrade",
                            TransactionDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -700.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 11,
                            Description = "Home improvement project",
                            Name = "Bathroom Renovation",
                            TransactionDate = new DateTime(2021, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -200.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 12,
                            Description = "Gift for spouse's anniversary",
                            Name = "Anniversary Gift",
                            TransactionDate = new DateTime(2023, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -50.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 13,
                            Description = "Summer vacation with family",
                            Name = "Beach Vacation",
                            TransactionDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -800.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 14,
                            Description = "Auto insurance premium",
                            Name = "Car Insurance",
                            TransactionDate = new DateTime(2021, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -90.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 15,
                            Description = "Back-to-school shopping",
                            Name = "School Supplies",
                            TransactionDate = new DateTime(2023, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -40.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 17,
                            Description = "Adding to investment portfolio",
                            Name = "Investment Portfolio",
                            TransactionDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = 300.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 20,
                            Description = "Purchase of home decor items",
                            Name = "Home Decor",
                            TransactionDate = new DateTime(2022, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -35.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Monthly phone plan bill",
                            Name = "Phone Bill",
                            TransactionDate = new DateTime(2022, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -40.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Description = "Ride to the airport",
                            Name = "Taxi Ride",
                            TransactionDate = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -25.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 15,
                            Description = "Monthly gym membership",
                            Name = "Fitness Membership",
                            TransactionDate = new DateTime(2023, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -60.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Description = "New books and magazines",
                            Name = "Bookstore Purchase",
                            TransactionDate = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -45.00m,
                            UserWalletId = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 11,
                            Description = "Routine car maintenance",
                            Name = "Car Maintenance",
                            TransactionDate = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransferredAmount = -80.00m,
                            UserWalletId = 1
                        });
                });

            modelBuilder.Entity("MVCBudget.Forser.Models.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10000m,
                            Name = "Marcus Wallet"
                        });
                });

            modelBuilder.Entity("MVCBudget.Forser.Models.Transaction", b =>
                {
                    b.HasOne("MVCBudget.Forser.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MVCBudget.Forser.Models.UserWallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserWalletId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVCBudget.Forser.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MVCBudget.Forser.Models.UserWallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
